# Generated by Django 2.1.3 on 2018-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181125_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_now=True, verbose_name='%m/%d/%Y %H:%M'),
        ),
    ]
