# Generated by Django 2.1.3 on 2018-11-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20181117_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
